using System.Text;
using IrOpCode = global::ObjectIR.Core.Ast.OpCode;

namespace lattice.Runtime.Compiler;

public static partial class CTranspiler
{
    public static string TranspileAll(IEnumerable<CompiledMethod> methods)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Lattice CTranspiler");
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine();
        foreach (var cm in methods)
            EmitMethod(sb, cm);
        return sb.ToString();
    }

    public static string TranspileMethod(CompiledMethod cm)
    {
        var sb = new StringBuilder();
        EmitMethod(sb, cm);
        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, CompiledMethod cm)
    {
        string retType = cm.ReturnsValue ? "int" : "void";
        string fnName = MangleName(cm.Name);
        var args = string.Join(", ", cm.ArgNames.Select((n, i) => $"int {MangleName(n)}"));

        sb.AppendLine($"static {retType} {fnName}({args}) {{");

        // local declarations
        if (cm.LocalCount > 0)
            sb.AppendLine("    int " + string.Join(", ", cm.LocalNames.Select(MangleName)) + ";");

        // Reset initial values to 0 (C semantics)
        foreach (var n in cm.LocalNames)
            sb.AppendLine($"    {MangleName(n)} = 0;");

        sb.AppendLine();

        // Walk bytecode, emit C statements
        var ctx = new EmitCtx(sb, cm);
        ctx.EmitBody();

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string MangleName(string n) =>
        "__" + n.Replace('.', '_').Replace(':', '_').Replace(' ', '_');

    private class EmitCtx
    {
        private readonly StringBuilder _sb;
        private readonly CompiledMethod _cm;
        private readonly CompactInstr[] _code;
        private readonly Stack<string> _expr = new();
        private int _ip;

        public EmitCtx(StringBuilder sb, CompiledMethod cm)
        {
            _sb = sb;
            _cm = cm;
            _code = cm.Code;
        }

        public void EmitBody()
        {
            while (_ip < _code.Length)
            {
                int blockStart = _ip;
                bool hasLabel = blockStart > 0 && IsBranchTarget(blockStart);
                if (hasLabel)
                    _sb.AppendLine($"L{blockStart}:");

                // Process instructions until we hit a branch or ret
                while (_ip < _code.Length)
                {
                    var instr = _code[_ip];
                    if (instr.Opcode is IrOpCode.Br or IrOpCode.Brfalse or IrOpCode.Brtrue or IrOpCode.Ret)
                    {
                        EmitBranch(instr);
                        _ip++;
                        break;
                    }
                    EmitOp(instr);
                    _ip++;
                }
            }
        }

        private void EmitOp(CompactInstr instr)
        {
            switch (instr.Opcode)
            {
                case IrOpCode.LdcI4:
                    _expr.Push(instr.Operand.ToString());
                    break;

                case IrOpCode.Ldloc:
                    _expr.Push(MangleName(_cm.LocalNames[instr.Operand]));
                    break;

                case IrOpCode.Ldarg:
                    _expr.Push(MangleName(_cm.ArgNames[instr.Operand]));
                    break;

                case IrOpCode.Stloc:
                    Assign(MangleName(_cm.LocalNames[instr.Operand]));
                    break;

                case IrOpCode.Starg:
                    Assign(MangleName(_cm.ArgNames[instr.Operand]));
                    break;

                case IrOpCode.Add:  Binary("+"); break;
                case IrOpCode.Sub:  Binary("-"); break;
                case IrOpCode.Mul:  Binary("*"); break;
                case IrOpCode.Div:  Binary("/"); break;
                case IrOpCode.Rem:  Binary("%"); break;

                case IrOpCode.Ceq:     Binary("=="); break;
                case IrOpCode.Cne:     Binary("!="); break;
                case IrOpCode.Cgt:     Binary(">");  break;
                case IrOpCode.Clt:     Binary("<");  break;
                case IrOpCode.CgtUn:   Binary(">");  break;
                case IrOpCode.CgeUn:   Binary(">="); break;

                case IrOpCode.Not:
                    if (_expr.Count >= 1) _expr.Push($"!({_expr.Pop()})");
                    break;

                case IrOpCode.Dup:
                    if (_expr.Count >= 1) _expr.Push(_expr.Peek());
                    break;

                case IrOpCode.Pop:
                    if (_expr.Count >= 1) { Line($"(void){_expr.Pop()};"); }
                    break;

                case IrOpCode.LdcR4:
                    _expr.Push(BitConverter.Int32BitsToSingle(instr.Operand).ToString("G"));
                    break;

                case IrOpCode.Ldnull:
                    _expr.Push("0");
                    break;

                default:
                    // Call, Newobj, Ldfld, Stfld, Ldstr — not yet implemented in C
                    break;
            }
        }

        private void EmitBranch(CompactInstr instr)
        {
            switch (instr.Opcode)
            {
                case IrOpCode.Ret:
                    if (_expr.Count >= 1)
                        Line($"return {_expr.Pop()};");
                    else
                        Line("return;");
                    break;

                case IrOpCode.Br:
                    Line($"goto L{instr.Operand};");
                    break;

                case IrOpCode.Brfalse:
                    if (_expr.Count >= 1)
                        Line($"if (!({_expr.Pop()})) goto L{instr.Operand};");
                    break;

                case IrOpCode.Brtrue:
                    if (_expr.Count >= 1)
                        Line($"if ({_expr.Pop()}) goto L{instr.Operand};");
                    break;
            }
        }

        private void Assign(string target)
        {
            if (_expr.Count >= 1)
                Line($"{target} = {_expr.Pop()};");
        }

        private void Binary(string op)
        {
            if (_expr.Count >= 2)
            {
                var b = _expr.Pop();
                var a = _expr.Pop();
                _expr.Push($"({a} {op} {b})");
            }
        }

        private void Line(string line) => _sb.AppendLine($"    {line}");

        private bool IsBranchTarget(int index)
        {
            for (int i = 0; i < _code.Length; i++)
            {
                var op = _code[i].Opcode;
                if ((op is IrOpCode.Br or IrOpCode.Brfalse or IrOpCode.Brtrue) && _code[i].Operand == index)
                    return true;
            }
            return false;
        }
    }
}
